name: Test Nix build

on:
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Verify flake
        run: nix flake show

      - name: Copy system emoji font
        run: cp "/System/Library/Fonts/Apple Color Emoji.ttc" emoji.ttc

      - name: Build package
        run: nix build .#default --override-input ttc path:./emoji.ttc --no-link
